# Generated by Django 4.2.8 on 2026-01-25 20:42

from django.db import migrations, models
import django.db.models.deletion


def create_categories(apps, schema_editor):
    """Create default categories from the old choices."""
    Category = apps.get_model('cavetechapp', 'Category')
    
    categories = [
        ('3d_printing', '3D Printing'),
        ('woodworking', 'Woodworking'),
        ('metalworking', 'Metalworking'),
        ('electronics', 'Electronics'),
        ('software', 'Software'),
        ('art', 'Art & Design'),
        ('robotics', 'Robotics'),
        ('other', 'Other'),
    ]
    
    for slug, name in categories:
        Category.objects.get_or_create(
            slug=slug,
            defaults={'name': name}
        )


def migrate_project_categories(apps, schema_editor):
    """Migrate existing projects to use Category foreign key."""
    Project = apps.get_model('cavetechapp', 'Project')
    Category = apps.get_model('cavetechapp', 'Category')
    
    category_map = {
        '3d_printing': '3d_printing',
        'woodworking': 'woodworking',
        'metalworking': 'metalworking',
        'electronics': 'electronics',
        'software': 'software',
        'art': 'art',
        'robotics': 'robotics',
        'other': 'other',
    }
    
    for project in Project.objects.all():
        if hasattr(project, '_state') and hasattr(project._state, 'adding'):
            continue
        
        old_category = getattr(project, 'category', None)
        if old_category:
            slug = category_map.get(old_category, 'other')
            category = Category.objects.get(slug=slug)
            project.category_id = category.id
            project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cavetechapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cavetechapp.category'),
        ),
        migrations.RunPython(create_categories),
        migrations.RunPython(migrate_project_categories),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category_new',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='cavetechapp.category'),
        ),
    ]
